# Generated by Django 6.0.2 on 2026-02-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Almost Delivered', max_length=50)),
            ],
        ),
    ]
